Syn 676
Syndicode/syndicode pull request #295
Opened 2022-06-27 18:31 UTC by tbunitrade

Updates for Contact Us page, delete Downloads move NDS link to bottom URL.

2022-06-27 18:53 UTC, LedangNguyen requested changes

2022-06-27 18:53 UTC, LedangNguyen commented on .gitignore
> +.gitignore
Remove this line

2022-06-27 18:53 UTC, LedangNguyen commented on .gitignore
> +wp-content/plugins/
Remove this line

2022-06-27 18:53 UTC, LedangNguyen commented on wp-content/themes/syndicode/inc/carbon-fields/blocks/template-services-new/engagement-models.php
> +						var_dump($data);
Is it supposed to be here?

2022-06-27 19:17 UTC, tbunitrade commented on .gitignore
> +.gitignore
OK

2022-06-28 08:02 UTC, LedangNguyen reviewed
Do we need Classic Editor?

2022-06-28 08:04 UTC, LedangNguyen commented on .gitignore
> +.gitignore
`.gitignore` still there

2022-06-28 13:37 UTC, LedangNguyen approved these changes

2022-06-28 13:38 UTC, merged